langs = [
"en" ,
"fr" ,
"es" ,
"es-mx",
"de" ,
"it" ,
"ja" ,
"pt-br",
"ru" ,
"pl" ,
"ko" ,
"zh-cht",
"zh-chs"
]

tables = ["DestinyArtDyeChannelDefinition",
"DestinyArtDyeReferenceDefinition",
"DestinyPlaceDefinition",
"DestinyActivityDefinition",
"DestinyActivityTypeDefinition",
"DestinyClassDefinition",
"DestinyGenderDefinition",
"DestinyInventoryBucketDefinition",
"DestinyRaceDefinition",
"DestinyUnlockDefinition",
"DestinyStatGroupDefinition",
"DestinyProgressionMappingDefinition",
"DestinyFactionDefinition",
"DestinyVendorGroupDefinition",
"DestinyRewardSourceDefinition",
"DestinyUnlockValueDefinition",
"DestinyRewardMappingDefinition",
"DestinyRewardSheetDefinition",
"DestinyItemCategoryDefinition",
"DestinyDamageTypeDefinition",
"DestinyActivityModeDefinition",
"DestinyMedalTierDefinition",
"DestinyAchievementDefinition",
"DestinyActivityGraphDefinition",
"DestinyActivityInteractableDefinition",
"DestinyBondDefinition",
"DestinyCharacterCustomizationCategoryDefinition",
"DestinyCharacterCustomizationOptionDefinition",
"DestinyCollectibleDefinition",
"DestinyDestinationDefinition",
"DestinyEntitlementOfferDefinition",
"DestinyEquipmentSlotDefinition",
"DestinyEventCardDefinition",
"DestinyFireteamFinderActivityGraphDefinition",
"DestinyFireteamFinderActivitySetDefinition",
"DestinyFireteamFinderLabelDefinition",
"DestinyFireteamFinderLabelGroupDefinition",
"DestinyFireteamFinderOptionDefinition",
"DestinyFireteamFinderOptionGroupDefinition",
"DestinyStatDefinition",
"DestinyInventoryItemDefinition",
"DestinyInventoryItemLiteDefinition",
"DestinyItemTierTypeDefinition",
"DestinyLoadoutColorDefinition",
"DestinyLoadoutIconDefinition",
"DestinyLoadoutNameDefinition",
"DestinyLocationDefinition",
"DestinyLoreDefinition",
"DestinyMaterialRequirementSetDefinition",
"DestinyMetricDefinition",
"DestinyObjectiveDefinition",
"DestinySandboxPerkDefinition",
"DestinyPlatformBucketMappingDefinition",
"DestinyPlugSetDefinition",
"DestinyPowerCapDefinition",
"DestinyPresentationNodeDefinition",
"DestinyProgressionDefinition",
"DestinyProgressionLevelRequirementDefinition",
"DestinyRecordDefinition",
"DestinyRewardAdjusterPointerDefinition",
"DestinyRewardAdjusterProgressionMapDefinition",
"DestinyRewardItemListDefinition",
"DestinySackRewardItemListDefinition",
"DestinySandboxPatternDefinition",
"DestinySeasonDefinition",
"DestinySeasonPassDefinition",
"DestinySocialCommendationDefinition",
"DestinySocketCategoryDefinition",
"DestinySocketTypeDefinition",
"DestinyTraitDefinition",
"DestinyUnlockCountMappingDefinition",
"DestinyUnlockEventDefinition",
"DestinyUnlockExpressionMappingDefinition",
"DestinyVendorDefinition",
"DestinyMilestoneDefinition",
"DestinyActivityModifierDefinition",
"DestinyReportReasonCategoryDefinition",
"DestinyArtifactDefinition",
"DestinyBreakerTypeDefinition",
"DestinyChecklistDefinition",
"DestinyEnergyTypeDefinition",
"DestinySocialCommendationNodeDefinition",
"DestinyGuardianRankDefinition",
"DestinyGuardianRankConstantsDefinition",
"DestinyLoadoutConstantsDefinition",
"DestinyFireteamFinderConstantsDefinition",
"DestinyGlobalConstantsDefinition"]